In [2]:
import numpy as np

In [2]:
upper_row = np.random.choice(2,size=5)
upper_row

array([0, 0, 1, 0, 1])

In [4]:
_temp = upper_row * np.arange(1,6)
_temp

array([0, 0, 3, 0, 5])

In [5]:
_temp[_temp > 0]

array([3, 5])

In [9]:
np.random.choice(_temp[_temp > 0])

3

In [3]:
upper_row = np.random.choice(2, size=5)
upper_row = (upper_row > -1 ) * 1
upper_row

array([1, 1, 1, 1, 1])